#!/bin/bash

# run the tests down at this directory
test_dir="`dirname $0`"

# TODO what if this directory is not writable?

sample_name="data-sample"

# a sample file to create a list of data files for testing
data_sample="$test_dir/$sample_name"
# a directory tree of data sample files
data_dir="$test_dir/data"
# where compressed file of various format will be generated and placed
tmp_dir="$test_dir/tmp"

# for debugging
#echo "test dir: $test_dir"
#echo "data sample file: $data_sample"

if [ ! -e $data_sample ]
then
  echo "creating a data sample file from $test_dir/../README"
  cp $test_dir/../README $data_sample
fi


# create a directory tree of data sample file
rm -r $data_dir >& /dev/null
if [ ! -e $data_dir ]
then
  mkdir $data_dir
fi

echo "creating a list of data sample files down at $data_dir"
for i in 0 1 2 3 4 5 6 7 8 9
do
  
  cp $data_sample $data_dir/$sample_name$i
done

# run tests
## create compressed files
rm -r $tmp_dir >& /dev/null
if [ ! -e $tmp_dir ]
then
  mkdir $tmp_dir
fi

echo "creating .7z compressed files down at $tmp_dir"
7z a "$tmp_dir/$sample_name.7z" $data_dir > /dev/null

echo "creating .zip compressed files down at $tmp_dir"
zip "$tmp_dir/$sample_name.zip" $data_dir > /dev/null

echo "creating .tar compressed files down at $tmp_dir"
tar -cf "$tmp_dir/$sample_name.tar" $data_dir > /dev/null

echo "creating .tar.bz2 compressed files down at $tmp_dir"
tar -cjf "$tmp_dir/$sample_name.tar.bz2" $data_dir > /dev/null

echo "creating .tar.gz compressed files down at $tmp_dir"
tar -czf "$tmp_dir/$sample_name.tar.gz" $data_dir > /dev/null

echo "creating .tgz compressed files down at $tmp_dir"
tar -czf "$tmp_dir/$sample_name.tgz" $data_dir > /dev/null

echo "creating .jar, .war and .ear compressed files down at $tmp_dir"
jar -cf "$tmp_dir/$sample_name.jar" $data_dir > /dev/null
jar -cf "$tmp_dir/$sample_name.war" $data_dir > /dev/null
jar -cf "$tmp_dir/$sample_name.ear" $data_dir > /dev/null

## run lily against compressed files
for file in $tmp_dir/*
do
  lily $file
done

# TODO: from data sample file create a list of files from which generate compressed files of all supported file formats
