#!/bin/bash
# lily is named after a girl's name.
# lily is used to preview compressed file before decompressing it.
# Before decompressing a tar file, a zip file or whatever compressed file, one
# would like to first list the contents of the file using commands like
# unzip -l xx.zip, tar -tvf xxx.tar.gz. This script will choose the right
# command for commonly used compressed file extension.

SUCCESS=0
E_NOARGS=65

if [ -z "$1" ]
then
  echo "Usage: `basename $0` compressed-file-name"
  exit $E_NOARGS
fi

unzip -l $1 | less
