#!/bin/bash
# Lily is named after a girl's name.
# Lily is used to preview compressed file before decompressing it.
# Before decompressing a tar file, a zip file or whatever compressed file, one
# would like to first list the contents of the file using commands like
# unzip -l xx.zip, tar -tvf xxx.tar.gz. This script will choose the right
# command for commonly used compressed file extension.
#
# Supported file formats are: .bz2*, .7z, .zip, .tar.bz2, .tar.gz, .tgz, .rar,
# .jar,  .war, .ear, .deb*, .rpm*. And more is coming up...
# *: temporarily not supported.

SUCCESS=0
E_NOARGS=65

if [ -z "$1" ]
then
  echo "Usage: `basename $0` compressed-file-name"
  exit $E_NOARGS
fi

get_file_type() {
  echo 'todo'
}

list_file_contents() {
  echo 'todo'
}

if echo "$1" | egrep '\.tar(\.(gz|bz2))?|\.tgz$' >& /dev/null
then
  tar -tvf $1 | less
elif echo "$1" | egrep '\.zip$|\.jar|\.war|\.ear' >& /dev/null
then
  unzip -l $1 | less
elif echo "$1" | egrep '\.7z|\.rar' >& /dev/null
then
  7z l $1 | less
else
  echo "The given file is in a unsupported file format!"
fi
